import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'ko' | 'en' | 'vn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ko: {
    // Nav
    'nav.tables': '테이블',
    'nav.orders': '주문현황',
    'nav.manage': '매장관리',
    
    // Header
    'header.title': '내 식당',
    'header.open': '영업중',
    
    // Tables
    'status.empty': '공석',
    'status.ordering': '주문중',
    'status.dining': '식사중',
    'status.cleaning': '청소필요',
    'table.guests': '명',
    'table.minutes': '분',
    'alert.calling': '직원 호출',
    'alert.new_order': '새 주문',
    
    // Order Feed
    'feed.title': '실시간 주문',
    'feed.empty': '모든 주문을 처리했습니다!',
    'feed.order': '주문',
    'feed.request': '요청',
    'feed.tab.new_orders': '새 주문',
    'feed.tab.cooking': '조리중',
    'btn.serve': '서빙완료',
    'btn.done': '확인완료',
    'btn.reply': '답장하기',
    'btn.send': '전송',
    'btn.cancel': '취소',
    'reply.select': '답장 선택:',
    'reply.sent_prefix': '전송됨: ',
    'reply.type_message': '답변을 입력하세요',
    'reply.placeholder': '답변을 입력하세요...',
    'msg.completed': '처리 완료되었습니다.',
    'msg.removed': '목록에서 삭제되었습니다.',
    'msg.new_order': '새 주문이 들어왔습니다.',
    
    // Quick Replies
    'reply.coming': '네, 바로 가져다 드릴게요! 🏃',
    'reply.wait': '잠시만 기다려 주세요 ⏳',
    'reply.soldout': '죄송합니다, 재료가 소진되었습니다 😢',
    'reply.kitchen': '주방에 전달했습니다 👨‍🍳',

    // Menu Manager
    'menu.title': '메뉴 관리',
    'menu.status': '메뉴 현황',
    'menu.items': '개 메뉴',
    'menu.soldout_count': '개 품절',
    'menu.soldout': '품절',
    'menu.manage_categories': '카테고리 관리',
    'menu.add_item': '메뉴 추가',
    'menu.no_options': '옵션 없음',
    'menu.option_groups': '개 옵션 그룹',
    'menu.on_sale': '판매중',
    'menu.basic_info': '기본 정보',
    'menu.item_name': '메뉴명',
    'menu.price': '가격',
    'menu.category': '카테고리',
    'menu.image_url': '이미지 URL',
    'menu.stock_status': '품절 상태',
    'menu.options_addons': '옵션 설정',
    'menu.add_group': '그룹 추가',
    'menu.group_name': '그룹명 (예: 맵기 조절)',
    'menu.min': '최소',
    'menu.max': '최대',
    'menu.option_name': '옵션명',
    'menu.add_choice': '선택지 추가',
    'menu.new_group': '새 옵션 그룹',
    
    // Dialogs & Sheets
    'dialog.cat.title': '카테고리 관리',
    'dialog.cat.desc': '카테고리를 추가하거나 삭제합니다.',
    'dialog.cat.placeholder': '새 카테고리 이름',
    'sheet.edit.title': '메뉴 수정',
    'sheet.edit.desc': '메뉴 상세 정보와 옵션을 수정합니다.',
    
    // Buttons
    'btn.add': '추가',
    'btn.delete': '삭제',
    'btn.save': '저장',
    
    // Messages
    'msg.cat_added': '카테고리가 추가되었습니다.',
    'msg.cat_deleted': '카테고리가 삭제되었습니다.',
    'msg.cat_has_items': '메뉴가 포함된 카테고리는 삭제할 수 없습니다.',
    'msg.item_saved': '메뉴가 저장되었습니다.',
    'msg.item_deleted': '메뉴가 삭제되었습니다.',
    'msg.name_required': '이름을 입력해주세요.',
    'msg.soldout_on': '품절 처리되었습니다.',
    'msg.soldout_off': '품절 해제되었습니다.',
    
    // Reports
    'nav.reports': '매출리포트',
    'report.title': '매출 대시보드',
    'report.today_revenue': '오늘 매출',
    'report.week_revenue': '주간 매출',
    'report.month_revenue': '월간 매출',
    'report.period_revenue': '총 매출',
    'report.total_orders': '총 주문수',
    'report.avg_order': '객단가',
    'report.turnover': '회전율',
    'report.weekly_trend': '주간 매출 추이',
    'report.hourly_traffic': '시간대별 주문',
    'report.orders_from_avg': '평균 대비',
    'report.top_items': '인기 메뉴 (Top 5)',
    'report.category_dist': '카테고리별 매출',
    'report.revenue': '매출액',
    'report.orders': '주문',
    'report.unit': '원',
    'report.per_order': '주문당',
    'report.no_data': '데이터가 없습니다',
    'report.sales_history': '매출 내역',
    'report.sales_history_today': '오늘의 주문 내역',
    'report.sales_history_week': '이번 주 주문 내역',
    'report.sales_history_month': '이번 달 주문 내역',
    'report.no_sales_history': '매출 내역이 없습니다.',
    'report.and_more': '외',
    'report.items': '개',
    'report.high_traffic': '높음',
    'report.moderate': '보통',
    'report.low_traffic': '낮음',
    'report.period': '기간 선택',
    'report.period_today': '오늘',
    'report.period_week': '이번 주',
    'report.period_month': '이번 달',
    'report.period_custom': '사용자 지정',
    'report.from_yesterday': '어제 대비',
    'report.select_date_range': '날짜 범위 선택',
    'report.date_range_prompt': '날짜 범위를 선택해주세요.',
    'report.loading': '로딩 중...',
    'report.error_failed': '리포트를 불러오는데 실패했습니다.',
    'table.number': '테이블',

    // Waiting List
    'wait.title': '대기 명단',
    'wait.add': '대기 등록',
    'wait.name': '이름',
    'wait.phone': '전화번호',
    'wait.guests': '인원',
    'wait.status': '상태',
    'wait.note': '메모',
    'wait.waiting': '대기중',
    'wait.notified': '호출됨',
    'wait.seated': '입장완료',
    'wait.cancelled': '취소됨',
    'wait.action_notify': '호출',
    'wait.action_seat': '입장',
    'wait.action_cancel': '취소',
    'wait.empty': '대기 손님이 없습니다.',
    'msg.wait_added': '대기 목록에 추가되었습니다.',
    'msg.wait_notified': '손님을 호출했습니다.',
    'msg.wait_seated': '입장 처리되었습니다.',
    'msg.wait_cancelled': '대기가 취소되었습니다.',

    // Settings & Staff
    'nav.settings': '설정',
    'settings.staff_title': '직원 관리',
    'settings.staff_desc': '매장 직원을 등록하고 권한을 관리합니다.',
    'settings.tab_menu': '메뉴',
    'settings.tab_tables': '테이블',
    'settings.tab_staff': '직원',
    'settings.tab_payment': '결제 방법',
    'payment.title': '결제 방법 관리',
    'payment.cash': '현금',
    'payment.card': '신용카드',
    'payment.bank_transfer': '계좌이체',
    'payment.enabled': '활성화',
    'payment.disabled': '비활성화',
    'payment.bank_name': '은행명',
    'payment.account_holder': '예금주명',
    'payment.account_number': '계좌번호',
    'payment.save': '저장',
    'payment.saved': '저장되었습니다',
    'order.entry.title': '주문 접수',
    'order.entry.select_menu': '메뉴 선택',
    'order.entry.cart': '장바구니',
    'order.entry.add_to_cart': '담기',
    'order.entry.create_order': '주문 생성',
    'order.entry.order_created': '주문이 생성되었습니다',
    'staff.add': '직원 등록',
    'staff.name': '이름',
    'staff.role': '역할',
    'staff.pin': 'PIN 번호',
    'staff.status': '상태',
    'staff.active': '재직중',
    'staff.inactive': '퇴사',
    'role.owner': '점장',
    'role.manager': '매니저',
    'role.kitchen': '주방',
    'role.hall': '홀',
    'role.staff': '사원',
    'msg.staff_added': '직원이 등록되었습니다.',
    'msg.staff_updated': '직원 정보가 수정되었습니다.',
    'msg.staff_deleted': '직원 정보가 삭제되었습니다.',
    
    // Auth & Login
    'auth.login_title': '매장 관리 시스템',
    'auth.login_desc': 'Google 계정으로 로그인하여 시작하세요.',
    'auth.google_login': 'Google로 계속하기',
    'auth.pending_title': '승인 대기 중',
    'auth.pending_desc': '관리자의 승인을 기다리고 있습니다. 승인이 완료되면 앱을 사용할 수 있습니다.',
    'auth.back_to_login': '로그인 화면으로 돌아가기',
    'auth.logout': '로그아웃',
    
    // Staff Approval
    'staff.tab_active': '직원 목록',
    'staff.tab_pending': '가입 대기',
    'staff.approve': '승인',
    'staff.reject': '거절',
    'msg.staff_approved': '직원 가입이 승인되었습니다.',
    'msg.staff_rejected': '가입 요청이 거절되었습니다.',
    
    // TableGrid Actions
    'table.action.seat_guests': '손님 착석',
    'table.action.start_dining': '식사 시작',
    'table.action.checkout_clear': '결제 및 정리',
    'table.action.mark_cleaned': '청소 완료',
    'table.action.manage': '테이블 관리',
    'table.detail.close': '닫기',
    'table.detail.orders': '주문',
    'table.detail.no_orders': '활성 주문 없음',
    'table.detail.total': '총액',
    'table.detail.guest_count': '인원 수',
    'table.detail.memo': '메모',
    'table.detail.select_table': '손님을 착석시킬 테이블을 선택하세요',
    'table.detail.parties_waiting': '팀 대기 중',
    'table.detail.select_empty_table': '빈 테이블을 선택하세요',
    'table.detail.active_requests': '활성 요청',
    'table.detail.chat': '채팅',
    'table.detail.no_messages': '메시지가 없습니다.',
    'table.status.call': '호출',
    'table.status.order': '주문',
    'table.status.cleaning': '청소 중',
    'table.error.update_failed': '테이블 상태 업데이트에 실패했습니다.',
    'table.error.guest_range': '인원 수는 {min}명부터 {max}명까지 가능합니다.',
    'table.error.no_orders': '주문 내역이 없습니다. 먼저 주문을 추가해주세요.',
    'table.success.guest_updated': '인원 수가 업데이트되었습니다.',
    'table.success.memo_updated': '메모가 업데이트되었습니다.',
    'order.action.start_cooking': '조리 시작',
    'order.action.mark_served': '서빙 완료',
    'order.status.updating': '업데이트 중...',
    'order.status.payment_pending': '결제 대기',
    'checkout.title': '결제',
    'checkout.orders': '주문 내역',
    'checkout.total': '총 결제 금액',
    'checkout.payment_method': '결제 방법',
    'checkout.cash': '현금',
    'checkout.card': '카드',
    'checkout.bank_transfer': '계좌이체',
    'checkout.complete': '결제 완료',
    'checkout.cancel': '취소',
    'checkout.select_method': '결제 방법을 선택하세요',
    'checkout.success': '결제가 완료되었습니다',
    
    // TableManagement
    'table.management.title': '테이블 관리',
    'table.management.total': '총 {count}개',
    'table.management.add_table': '테이블 추가',
    'table.management.floor': '층',
    'table.management.capacity': '수용 인원',
    'table.management.table_number': '테이블 번호',
    'table.management.delete': '삭제',
    'table.management.edit': '수정',
    'table.management.active': '활성',
    'table.management.inactive': '비활성',
    'table.error.restaurant_id_required': '식당 ID가 필요합니다.',
    'table.error.invalid_number': '유효한 숫자를 입력해주세요.',
    'table.error.min_capacity': '수용 인원은 최소 1명 이상이어야 합니다.',
    'table.error.min_floor': '층수는 최소 1층 이상이어야 합니다.',
    'table.success.updated': '테이블이 성공적으로 수정되었습니다.',
    'table.success.added': '테이블이 성공적으로 추가되었습니다.',
    'table.success.deleted': '테이블이 성공적으로 삭제되었습니다.',
    'table.management.empty': '등록된 테이블이 없습니다',
    'table.management.edit_table': '테이블 수정',
    'table.management.add_new_table': '새 테이블 추가',
    'table.management.configure_desc': '테이블 번호와 수용 인원을 설정합니다.',
    'table.management.table_number_label': '테이블 번호',
    'table.management.table_number_placeholder': '예: 1, 2, 3',
    'table.management.table_number_desc': '테이블 카드에 표시됩니다.',
    'table.management.floor_label': '층',
    'table.management.floor_placeholder': '예: 1',
    'table.management.floor_desc': '이 테이블이 위치한 층을 입력하세요.',
    'table.management.capacity_label': '수용 인원',
    'table.management.capacity_placeholder': '예: 4',
    'table.management.capacity_desc': '이 테이블의 최대 인원 수입니다.',
    'table.management.table_label': '테이블 {number}',
    'table.management.edit_details': '상세 수정',
    'table.management.delete_confirm': '테이블 {number}번을 삭제하시겠습니까?',
    'table.management.saving': '저장 중...',
    'table.management.save_changes': '변경 사항 저장',
    'table.management.add_table_button': '테이블 추가',
    'table.error.table_not_found': '테이블을 찾을 수 없습니다',
    'table.error.cannot_delete_active': '활성 상태인 테이블은 삭제할 수 없습니다. 먼저 비워주세요.',
    
    // OrderEntrySheet
    'order.entry.table_number': '테이블 {number}',
    'order.entry.creating': '주문 중...',
    
    // WaitingListPanel Actions
    'wait.action.edit': '수정',
    'wait.action.cancel': '취소',
    'wait.action.delete': '삭제',
    'wait.saving': '저장 중...',
    
    // LoginScreen
    'login.error.restaurant_load_failed': '식당 정보를 불러오는데 실패했습니다.',
    'login.error.restaurant_not_found': '식당을 찾을 수 없습니다. 식당 ID를 확인해주세요.',
    'login.error.restaurant_id_required': '식당 ID가 필요합니다.',
    'login.mode.admin': '관리자 로그인',
    'login.mode.pin': 'POS 로그인 (PIN)',
    'login.title.who_logging_in': '누가 로그인하시나요?',
    'login.pin.enter_pin': 'PIN 입력',
    'login.success.welcome_back': '다시 오신 것을 환영합니다, {name}님!',
    
    // Notifications
    'notification.title': '알림',
    'notification.unread': '읽지 않음',
    'notification.mark_all_read': '모두 읽음으로 표시',
    'notification.new_order': '새 주문 #{number}',
    'notification.table_placed_order': '테이블 {number}에서 새 주문',
    'notification.water_request': '물 요청',
    'notification.table_needs_water': '테이블 {number}에서 물이 필요합니다',
    'notification.customer_request': '고객 요청',
    'notification.table_has_request': '테이블 {number}에서 요청이 있습니다',
    'notification.payment_confirmed': '결제 확인됨',
    'notification.table_paid': '테이블 {number}에서 {amount} 결제',
    'notification.shift_alert': '교대 알림',
    'notification.break_time_starts': '휴식 시간 {minutes}분 후 시작',
    'notification.just_now': '방금',
    'notification.time_ago': '{minutes}분 전',
    'notification.hour_ago': '{hours}시간 전',
    'notification.no_more': '더 이상 알림이 없습니다',
    'notification.tab.all': '전체',
    'notification.tab.unread': '안읽음',
    'notification.tab.orders': '주문',
    'notification.tab.requests': '요청',
    'notification.tab.chat': '채팅',
    'notification.tab.payment': '결제',
    'notification.tab.other': '기타',
  },
  en: {
    'nav.tables': 'Tables',
    'nav.orders': 'Orders',
    'nav.manage': 'Manage',
    'header.title': 'My Restaurant',
    'header.open': 'Open',
    'status.empty': 'Empty',
    'status.ordering': 'Ordering',
    'status.dining': 'Dining',
    'status.cleaning': 'Clean',
    'table.guests': 'guests',
    'table.minutes': 'm',
    'alert.calling': 'CALLING',
    'alert.new_order': 'NEW ORDER',
    'feed.title': 'Live Feed',
    'feed.empty': 'All caught up!',
    'feed.order': 'Order',
    'feed.request': 'Request',
    'feed.tab.new_orders': 'New Orders',
    'feed.tab.cooking': 'Cooking',
    'btn.serve': 'Serve',
    'btn.done': 'Done',
    'btn.reply': 'Reply',
    'btn.send': 'Send',
    'btn.cancel': 'Cancel',
    'reply.select': 'Select reply:',
    'reply.sent_prefix': 'Sent: ',
    'reply.type_message': 'Type your reply',
    'reply.placeholder': 'Type your reply...',
    'msg.completed': 'Marked as completed.',
    'msg.removed': 'Removed from list.',
    'msg.new_order': 'New order received.',
    'reply.coming': 'Coming right up! 🏃',
    'reply.wait': 'Please wait a moment ⏳',
    'reply.soldout': 'Sorry, this item is sold out 😢',
    'reply.kitchen': 'Relayed to kitchen 👨‍🍳',
    'menu.title': 'Menu Management',
    'menu.status': 'Menu Status',
    'menu.items': 'items',
    'menu.soldout_count': 'Sold Out',
    'menu.soldout': 'Sold Out',
    'menu.manage_categories': 'Manage Categories',
    'menu.add_item': 'Add Item',
    'menu.no_options': 'No options',
    'menu.option_groups': 'Option Groups',
    'menu.on_sale': 'On Sale',
    'menu.basic_info': 'Basic Information',
    'menu.item_name': 'Item Name',
    'menu.price': 'Price',
    'menu.category': 'Category',
    'menu.image_url': 'Image URL',
    'menu.stock_status': 'Stock Status',
    'menu.options_addons': 'Options & Add-ons',
    'menu.add_group': 'Add Group',
    'menu.group_name': 'Group Name (e.g. Spiciness)',
    'menu.min': 'Min',
    'menu.max': 'Max',
    'menu.option_name': 'Option Name',
    'menu.add_choice': 'Add Choice',
    'menu.new_group': 'New Option Group',
    
    // Dialogs & Sheets
    'dialog.cat.title': 'Manage Categories',
    'dialog.cat.desc': 'Add or remove menu categories.',
    'dialog.cat.placeholder': 'New Category Name',
    'sheet.edit.title': 'Edit Menu Item',
    'sheet.edit.desc': 'Modify item details, pricing, and options.',
    
    // Buttons
    'btn.add': 'Add',
    'btn.delete': 'Delete',
    'btn.save': 'Save Changes',
    
    // Messages
    'msg.cat_added': 'Category added.',
    'msg.cat_deleted': 'Category deleted.',
    'msg.cat_has_items': 'Cannot delete category with items.',
    'msg.item_saved': 'Menu item saved.',
    'msg.item_deleted': 'Menu item deleted.',
    'msg.name_required': 'Name is required.',
    'msg.soldout_on': 'Marked as Sold Out',
    'msg.soldout_off': 'Back in stock',

    // Reports
    'nav.reports': 'Reports',
    'report.title': 'Revenue Dashboard',
    'report.today_revenue': 'Today Revenue',
    'report.week_revenue': 'Weekly Revenue',
    'report.month_revenue': 'Monthly Revenue',
    'report.period_revenue': 'Total Revenue',
    'report.total_orders': 'Total Orders',
    'report.avg_order': 'Avg Order Value',
    'report.turnover': 'Turnover',
    'report.weekly_trend': 'Weekly Revenue Trend',
    'report.top_items': 'Top Selling Items',
    'report.category_dist': 'Sales by Category',
    'report.revenue': 'Revenue',
    'report.orders': 'Orders',
    'report.unit': '',
    'report.per_order': 'Per order',
    'report.no_data': 'No data available',
    'report.hourly_traffic': 'Hourly Traffic',
    'report.orders_from_avg': 'orders from avg',
    'report.sales_history': 'Sales History',
    'report.sales_history_today': "Today's Orders",
    'report.sales_history_week': "This Week's Orders",
    'report.sales_history_month': "This Month's Orders",
    'report.no_sales_history': 'No sales history available.',
    'report.and_more': 'and',
    'report.items': 'items',
    'report.high_traffic': 'High traffic',
    'report.moderate': 'Moderate',
    'report.low_traffic': 'Low traffic',
    'report.period': 'Select Period',
    'report.period_today': 'Today',
    'report.period_week': 'This Week',
    'report.period_month': 'This Month',
    'report.period_custom': 'Custom Range',
    'report.from_yesterday': 'from yesterday',
    'report.select_date_range': 'Select date range',
    'report.date_range_prompt': 'Please select a date range.',
    'report.loading': 'Loading...',
    'report.error_failed': 'Failed to load report.',
    'table.number': 'Table',

    // Waiting List
    'wait.title': 'Waiting List',
    'wait.add': 'Add Party',
    'wait.name': 'Name',
    'wait.phone': 'Phone',
    'wait.guests': 'Guests',
    'wait.status': 'Status',
    'wait.note': 'Note',
    'wait.waiting': 'Waiting',
    'wait.notified': 'Notified',
    'wait.seated': 'Seated',
    'wait.cancelled': 'Cancelled',
    'wait.action_notify': 'Notify',
    'wait.action_seat': 'Seat',
    'wait.action_cancel': 'Cancel',
    'wait.empty': 'No waiting guests.',
    'msg.wait_added': 'Added to waiting list.',
    'msg.wait_notified': 'Guest notified.',
    'msg.wait_seated': 'Guest seated.',
    'msg.wait_cancelled': 'Waiting cancelled.',

    // Settings & Staff
    'nav.settings': 'Settings',
    'settings.staff_title': 'Team Management',
    'settings.staff_desc': 'Manage staff access and roles.',
    'settings.tab_menu': 'Menu',
    'settings.tab_tables': 'Tables',
    'settings.tab_staff': 'Staff',
    'settings.tab_payment': 'Payment Methods',
    'payment.title': 'Payment Methods Management',
    'payment.cash': 'Cash',
    'payment.card': 'Credit Card',
    'payment.bank_transfer': 'Bank Transfer',
    'payment.enabled': 'Enabled',
    'payment.disabled': 'Disabled',
    'payment.bank_name': 'Bank Name',
    'payment.account_holder': 'Account Holder',
    'payment.account_number': 'Account Number',
    'payment.save': 'Save',
    'payment.saved': 'Saved',
    'order.entry.title': 'Order Entry',
    'order.entry.select_menu': 'Select Menu',
    'order.entry.cart': 'Cart',
    'order.entry.add_to_cart': 'Add to Cart',
    'order.entry.create_order': 'Create Order',
    'order.entry.order_created': 'Order created',
    'staff.add': 'Add Member',
    'staff.name': 'Name',
    'staff.role': 'Role',
    'staff.pin': 'PIN Code',
    'staff.status': 'Status',
    'staff.active': 'Active',
    'staff.inactive': 'Inactive',
    'role.owner': 'Owner',
    'role.manager': 'Manager',
    'role.kitchen': 'Kitchen',
    'role.hall': 'Hall',
    'role.staff': 'Staff',
    'msg.staff_added': 'Team member added.',
    'msg.staff_updated': 'Member updated.',
    'msg.staff_deleted': 'Member removed.',

    // Auth & Login
    'auth.login_title': 'Store Management',
    'auth.login_desc': 'Sign in with Google to continue.',
    'auth.google_login': 'Continue with Google',
    'auth.pending_title': 'Approval Pending',
    'auth.pending_desc': 'Your account is waiting for manager approval.',
    'auth.back_to_login': 'Back to Login',
    'auth.logout': 'Sign Out',

    // Staff Approval
    'staff.tab_active': 'Active Staff',
    'staff.tab_pending': 'Pending Requests',
    'staff.approve': 'Approve',
    'staff.reject': 'Reject',
    'msg.staff_approved': 'Member approved.',
    'msg.staff_rejected': 'Request rejected.',
    
    // TableGrid Actions
    'table.action.seat_guests': 'Seat Guests',
    'table.action.start_dining': 'Start Dining',
    'table.action.checkout_clear': 'Checkout & Clear',
    'table.action.mark_cleaned': 'Mark Cleaned',
    'table.action.manage': 'Manage Table',
    'table.detail.close': 'Close',
    'table.detail.orders': 'Orders',
    'table.detail.no_orders': 'No active orders',
    'table.detail.total': 'Total',
    'table.detail.guest_count': 'Guest Count',
    'table.detail.memo': 'Memo',
    'table.detail.select_table': 'Select a table to seat guests',
    'table.detail.parties_waiting': 'parties waiting',
    'table.detail.select_empty_table': 'Select an empty table to assign',
    'table.detail.active_requests': 'Active Requests',
    'table.detail.chat': 'Chat',
    'table.detail.no_messages': 'No messages',
    'table.status.call': 'Call',
    'table.status.order': 'Order',
    'table.status.cleaning': 'Cleaning',
    'table.error.update_failed': 'Failed to update table status.',
    'table.error.guest_range': 'Guests must be between {min} and {max}.',
    'table.error.no_orders': 'No orders found. Please add orders first.',
    'table.success.guest_updated': 'Guest count updated.',
    'table.success.memo_updated': 'Memo updated.',
    'order.action.start_cooking': 'Start Cooking',
    'order.action.mark_served': 'Mark Served',
    'order.status.updating': 'Updating...',
    'order.status.payment_pending': 'Payment Pending',
    'checkout.title': 'Checkout',
    'checkout.orders': 'Orders',
    'checkout.total': 'Total Amount',
    'checkout.payment_method': 'Payment Method',
    'checkout.cash': 'Cash',
    'checkout.card': 'Card',
    'checkout.bank_transfer': 'Bank Transfer',
    'checkout.complete': 'Complete Payment',
    'checkout.cancel': 'Cancel',
    'checkout.select_method': 'Please select a payment method',
    'checkout.success': 'Payment completed successfully',
    
    // TableManagement
    'table.management.title': 'Table Management',
    'table.management.total': 'Total {count}',
    'table.management.add_table': 'Add Table',
    'table.management.floor': 'Floor',
    'table.management.capacity': 'Capacity',
    'table.management.table_number': 'Table Number',
    'table.management.delete': 'Delete',
    'table.management.edit': 'Edit',
    'table.management.active': 'ACTIVE',
    'table.management.inactive': 'INACTIVE',
    'table.error.restaurant_id_required': 'Restaurant ID is required.',
    'table.error.invalid_number': 'Please enter a valid number.',
    'table.error.min_capacity': 'Capacity must be at least 1.',
    'table.error.min_floor': 'Floor must be at least 1.',
    'table.success.updated': 'Table updated successfully.',
    'table.success.added': 'Table added successfully.',
    'table.success.deleted': 'Table deleted successfully.',
    'table.management.empty': 'No tables registered',
    'table.management.edit_table': 'Edit Table',
    'table.management.add_new_table': 'Add New Table',
    'table.management.configure_desc': 'Configure table number and seating capacity.',
    'table.management.table_number_label': 'Table Number',
    'table.management.table_number_placeholder': 'e.g. 1, 2, 3',
    'table.management.table_number_desc': 'This will be displayed on the table card.',
    'table.management.floor_label': 'Floor Level',
    'table.management.floor_placeholder': 'e.g. 1',
    'table.management.floor_desc': 'Which floor is this table located on?',
    'table.management.capacity_label': 'Seating Capacity',
    'table.management.capacity_placeholder': 'e.g. 4',
    'table.management.capacity_desc': 'Maximum number of guests for this table.',
    'table.management.table_label': 'Table {number}',
    'table.management.edit_details': 'Edit Details',
    'table.management.delete_confirm': 'Are you sure you want to delete table {number}?',
    'table.management.saving': 'Saving...',
    'table.management.save_changes': 'Save Changes',
    'table.management.add_table_button': 'Add Table',
    'table.error.table_not_found': 'Table not found',
    'table.error.cannot_delete_active': 'Cannot delete active table. Please clear it first.',
    
    // OrderEntrySheet
    'order.entry.table_number': 'Table {number}',
    'order.entry.creating': 'Creating order...',
    
    // WaitingListPanel Actions
    'wait.action.edit': 'Edit',
    'wait.action.cancel': 'Cancel',
    'wait.action.delete': 'Delete',
    'wait.saving': 'Saving...',
    
    // LoginScreen
    'login.error.restaurant_load_failed': 'Failed to load restaurant information.',
    'login.error.restaurant_not_found': 'Restaurant not found. Please check the restaurant ID.',
    'login.error.restaurant_id_required': 'Restaurant ID is required.',
    'login.mode.admin': 'Admin Login',
    'login.mode.pin': 'POS Login (PIN)',
    'login.title.who_logging_in': 'Who is logging in?',
    'login.pin.enter_pin': 'Enter PIN',
    'login.success.welcome_back': 'Welcome back, {name}!',
    
    // Notifications
    'notification.title': 'Notifications',
    'notification.unread': 'Unread',
    'notification.mark_all_read': 'Mark all read',
    'notification.new_order': 'New Order #{number}',
    'notification.table_placed_order': 'Table {number} placed a new order',
    'notification.water_request': 'Water Request',
    'notification.table_needs_water': 'Table {number} needs water',
    'notification.customer_request': 'Customer Request',
    'notification.table_has_request': 'Table {number} has a request',
    'notification.payment_confirmed': 'Payment Confirmed',
    'notification.table_paid': 'Table {number} paid {amount}',
    'notification.shift_alert': 'Shift Alert',
    'notification.break_time_starts': 'Break time starts in {minutes}m',
    'notification.just_now': 'Just now',
    'notification.time_ago': '{minutes}m ago',
    'notification.hour_ago': '{hours}h ago',
    'notification.no_more': 'No more notifications',
    'notification.tab.all': 'All',
    'notification.tab.unread': 'Unread',
    'notification.tab.orders': 'Orders',
    'notification.tab.requests': 'Requests',
    'notification.tab.chat': 'Chat',
    'notification.tab.payment': 'Payment',
    'notification.tab.other': 'Other',
  },
  vn: {
    'nav.tables': 'Bàn',
    'nav.orders': 'Đơn hàng',
    'nav.manage': 'Quản lý',
    'header.title': 'Nhà hàng của tôi',
    'header.open': 'Đang mở',
    'status.empty': 'Trống',
    'status.ordering': 'Đang gọi',
    'status.dining': 'Đang ăn',
    'status.cleaning': 'Dọn dẹp',
    'table.guests': 'khách',
    'table.minutes': 'phút',
    'alert.calling': 'GỌI NV',
    'alert.new_order': 'ĐƠN MỚI',
    'feed.title': 'Trực tiếp',
    'feed.empty': 'Đã xong hết!',
    'feed.order': 'Đơn món',
    'feed.request': 'Yêu cầu',
    'feed.tab.new_orders': 'Đơn mới',
    'feed.tab.cooking': 'Đang nấu',
    'btn.serve': 'Đã phục vụ',
    'btn.done': 'Xong',
    'btn.reply': 'Trả lời',
    'btn.send': 'Gửi',
    'btn.cancel': 'Hủy',
    'reply.select': 'Chọn câu trả lời:',
    'reply.sent_prefix': 'Đã gửi: ',
    'reply.type_message': 'Nhập câu trả lời của bạn',
    'reply.placeholder': 'Nhập câu trả lời của bạn...',
    'msg.completed': 'Đã hoàn thành.',
    'msg.removed': 'Đã xóa khỏi danh sách.',
    'msg.new_order': 'Có đơn hàng mới.',
    'reply.coming': 'Vâng, tôi sẽ mang đến ngay! 🏃',
    'reply.wait': 'Vui lòng đợi một lát ⏳',
    'reply.soldout': 'Xin lỗi, món này đã hết 😢',
    'reply.kitchen': 'Đã báo bếp 👨‍🍳',
    'menu.title': 'Quản lý thực đơn',
    'menu.status': 'Trạng thái thực đơn',
    'menu.items': 'món',
    'menu.soldout_count': 'Đã hết',
    'menu.soldout': 'Hết hàng',
    'menu.manage_categories': 'Quản lý danh mục',
    'menu.add_item': 'Thêm món',
    'menu.no_options': 'Không có tùy chọn',
    'menu.option_groups': 'Nhóm tùy chọn',
    'menu.on_sale': 'Đang bán',
    'menu.basic_info': 'Thông tin cơ bản',
    'menu.item_name': 'Tên món',
    'menu.price': 'Giá',
    'menu.category': 'Danh mục',
    'menu.image_url': 'URL Hình ảnh',
    'menu.stock_status': 'Tình trạng kho',
    'menu.options_addons': 'Tùy chọn & Thêm',
    'menu.add_group': 'Thêm nhóm',
    'menu.group_name': 'Tên nhóm (vd: Độ cay)',
    'menu.min': 'Min',
    'menu.max': 'Max',
    'menu.option_name': 'Tên tùy chọn',
    'menu.add_choice': 'Thêm lựa chọn',
    'menu.new_group': 'Nhóm tùy chọn mới',
    
    // Dialogs & Sheets
    'dialog.cat.title': 'Quản lý danh mục',
    'dialog.cat.desc': 'Thêm hoặc xóa danh mục thực đơn.',
    'dialog.cat.placeholder': 'Tên danh mục mới',
    'sheet.edit.title': 'Sửa món',
    'sheet.edit.desc': 'Sửa chi tiết món, giá và tùy chọn.',
    
    // Buttons
    'btn.add': 'Thêm',
    'btn.delete': 'Xóa',
    'btn.save': 'Lưu thay đổi',
    
    // Messages
    'msg.cat_added': 'Đã thêm danh mục.',
    'msg.cat_deleted': 'Đã xóa danh mục.',
    'msg.cat_has_items': 'Không thể xóa danh mục đang có món.',
    'msg.item_saved': 'Đã lưu món.',
    'msg.item_deleted': 'Đã xóa món.',
    'msg.name_required': 'Yêu cầu nhập tên.',
    'msg.soldout_on': 'Đã đánh dấu hết hàng',
    'msg.soldout_off': 'Đã có hàng lại',

    // Reports
    'nav.reports': 'Báo cáo',
    'report.title': 'Bảng doanh thu',
    'report.today_revenue': 'Doanh thu hôm nay',
    'report.week_revenue': 'Doanh thu tuần',
    'report.month_revenue': 'Doanh thu tháng',
    'report.period_revenue': 'Tổng doanh thu',
    'report.total_orders': 'Tổng đơn',
    'report.avg_order': 'Giá trị TB',
    'report.turnover': 'Vòng quay',
    'report.weekly_trend': 'Xu hướng tuần',
    'report.top_items': 'Món bán chạy',
    'report.category_dist': 'Theo danh mục',
    'report.revenue': 'Doanh thu',
    'report.orders': 'Đơn hàng',
    'report.unit': 'đ',
    'report.per_order': 'Mỗi đơn',
    'report.no_data': 'Không có dữ liệu',
    'report.hourly_traffic': 'Đơn hàng theo giờ',
    'report.orders_from_avg': 'đơn so với trung bình',
    'report.sales_history': 'Lịch sử bán hàng',
    'report.sales_history_today': 'Đơn hàng hôm nay',
    'report.sales_history_week': 'Đơn hàng tuần này',
    'report.sales_history_month': 'Đơn hàng tháng này',
    'report.no_sales_history': 'Không có lịch sử bán hàng.',
    'report.and_more': 'và',
    'report.items': 'món',
    'report.high_traffic': 'Cao',
    'report.moderate': 'Trung bình',
    'report.low_traffic': 'Thấp',
    'report.period': 'Chọn khoảng thời gian',
    'report.period_today': 'Hôm nay',
    'report.period_week': 'Tuần này',
    'report.period_month': 'Tháng này',
    'report.period_custom': 'Tùy chỉnh',
    'report.from_yesterday': 'so với hôm qua',
    'report.select_date_range': 'Chọn khoảng thời gian',
    'report.date_range_prompt': 'Vui lòng chọn khoảng thời gian.',
    'report.loading': 'Đang tải...',
    'report.error_failed': 'Không thể tải báo cáo.',
    'table.number': 'Bàn',

    // Waiting List
    'wait.title': 'Danh sách chờ',
    'wait.add': 'Thêm khách',
    'wait.name': 'Tên',
    'wait.phone': 'SĐT',
    'wait.guests': 'Khách',
    'wait.status': 'Trạng thái',
    'wait.note': 'Ghi chú',
    'wait.waiting': 'Đang chờ',
    'wait.notified': 'Đã gọi',
    'wait.seated': 'Đã ngồi',
    'wait.cancelled': 'Đã hủy',
    'wait.action_notify': 'Gọi',
    'wait.action_seat': 'Xếp bàn',
    'wait.action_cancel': 'Hủy',
    'wait.empty': 'Không có khách chờ.',
    'msg.wait_added': 'Đã thêm vào danh sách chờ.',
    'msg.wait_notified': 'Đã thông báo cho khách.',
    'msg.wait_seated': 'Đã xếp bàn xong.',
    'msg.wait_cancelled': 'Đã hủy chờ.',

    // Settings & Staff
    'nav.settings': 'Cài đặt',
    'settings.staff_title': 'Quản lý nhân viên',
    'settings.staff_desc': 'Quản lý nhân viên và quyền truy cập.',
    'settings.tab_menu': 'Thực đơn',
    'settings.tab_tables': 'Bàn',
    'settings.tab_staff': 'Nhân viên',
    'settings.tab_payment': 'Phương thức thanh toán',
    'payment.title': 'Quản lý phương thức thanh toán',
    'payment.cash': 'Tiền mặt',
    'payment.card': 'Thẻ tín dụng',
    'payment.bank_transfer': 'Chuyển khoản ngân hàng',
    'payment.enabled': 'Kích hoạt',
    'payment.disabled': 'Vô hiệu hóa',
    'payment.bank_name': 'Tên ngân hàng',
    'payment.account_holder': 'Chủ tài khoản',
    'payment.account_number': 'Số tài khoản',
    'payment.save': 'Lưu',
    'payment.saved': 'Đã lưu',
    'order.entry.title': 'Nhận đơn hàng',
    'order.entry.select_menu': 'Chọn món',
    'order.entry.cart': 'Giỏ hàng',
    'order.entry.add_to_cart': 'Thêm vào giỏ',
    'order.entry.create_order': 'Tạo đơn hàng',
    'order.entry.order_created': 'Đơn hàng đã được tạo',
    'staff.add': 'Thêm nhân viên',
    'staff.name': 'Tên',
    'staff.role': 'Vai trò',
    'staff.pin': 'Mã PIN',
    'staff.status': 'Trạng thái',
    'staff.active': 'Đang làm',
    'staff.inactive': 'Đã nghỉ',
    'role.owner': 'Chủ quán',
    'role.manager': 'Quản lý',
    'role.kitchen': 'Bếp',
    'role.hall': 'Sảnh',
    'role.staff': 'Nhân viên',
    'msg.staff_added': 'Đã thêm nhân viên.',
    'msg.staff_updated': 'Đã cập nhật nhân viên.',
    'msg.staff_deleted': 'Đã xóa nhân viên.',

    // Auth & Login
    'auth.login_title': 'Quản lý cửa hàng',
    'auth.login_desc': 'Đăng nhập bằng Google để tiếp tục.',
    'auth.google_login': 'Tiếp tục với Google',
    'auth.pending_title': 'Đang chờ duyệt',
    'auth.pending_desc': 'Tài khoản của bạn đang chờ quản lý phê duyệt.',
    'auth.back_to_login': 'Quay lại đăng nhập',
    'auth.logout': 'Đăng xuất',

    // Staff Approval
    'staff.tab_active': 'Nhân viên',
    'staff.tab_pending': 'Chờ duyệt',
    'staff.approve': 'Duyệt',
    'staff.reject': 'Từ chối',
    'msg.staff_approved': 'Đã duyệt nhân viên.',
    'msg.staff_rejected': 'Đã từ chối yêu cầu.',
    
    // TableGrid Actions
    'table.action.seat_guests': 'Xếp khách',
    'table.action.start_dining': 'Bắt đầu ăn',
    'table.action.checkout_clear': 'Thanh toán & Dọn dẹp',
    'table.action.mark_cleaned': 'Đã dọn xong',
    'table.action.manage': 'Quản lý bàn',
    'table.detail.close': 'Đóng',
    'table.detail.orders': 'Đơn hàng',
    'table.detail.no_orders': 'Không có đơn hàng',
    'table.detail.total': 'Tổng',
    'table.detail.guest_count': 'Số khách',
    'table.detail.memo': 'Ghi chú',
    'table.detail.select_table': 'Chọn bàn để xếp khách',
    'table.detail.parties_waiting': 'nhóm đang chờ',
    'table.detail.select_empty_table': 'Chọn bàn trống để gán',
    'table.detail.active_requests': 'Yêu cầu đang hoạt động',
    'table.detail.chat': 'Trò chuyện',
    'table.detail.no_messages': 'Không có tin nhắn',
    'table.status.call': 'Gọi',
    'table.status.order': 'Đơn hàng',
    'table.status.cleaning': 'Đang dọn',
    'table.error.update_failed': 'Không thể cập nhật trạng thái bàn.',
    'table.error.guest_range': 'Số khách phải từ {min} đến {max}.',
    'table.error.no_orders': 'Không có đơn hàng. Vui lòng thêm đơn hàng trước.',
    'table.success.guest_updated': 'Đã cập nhật số khách.',
    'table.success.memo_updated': 'Đã cập nhật ghi chú.',
    'order.action.start_cooking': 'Bắt đầu nấu',
    'order.action.mark_served': 'Đã phục vụ',
    'order.status.updating': 'Đang cập nhật...',
    'order.status.payment_pending': 'Chờ thanh toán',
    'checkout.title': 'Thanh toán',
    'checkout.orders': 'Đơn hàng',
    'checkout.total': 'Tổng tiền',
    'checkout.payment_method': 'Phương thức thanh toán',
    'checkout.cash': 'Tiền mặt',
    'checkout.card': 'Thẻ',
    'checkout.bank_transfer': 'Chuyển khoản',
    'checkout.complete': 'Hoàn tất thanh toán',
    'checkout.cancel': 'Hủy',
    'checkout.select_method': 'Vui lòng chọn phương thức thanh toán',
    'checkout.success': 'Thanh toán thành công',
    
    // TableManagement
    'table.management.title': 'Quản lý bàn',
    'table.management.total': 'Tổng {count}',
    'table.management.add_table': 'Thêm bàn',
    'table.management.floor': 'Tầng',
    'table.management.capacity': 'Sức chứa',
    'table.management.table_number': 'Số bàn',
    'table.management.delete': 'Xóa',
    'table.management.edit': 'Sửa',
    'table.management.active': 'HOẠT ĐỘNG',
    'table.management.inactive': 'KHÔNG HOẠT ĐỘNG',
    'table.error.restaurant_id_required': 'Cần ID nhà hàng.',
    'table.error.invalid_number': 'Vui lòng nhập số hợp lệ.',
    'table.error.min_capacity': 'Sức chứa phải ít nhất 1 người.',
    'table.error.min_floor': 'Tầng phải ít nhất 1.',
    'table.success.updated': 'Đã cập nhật bàn thành công.',
    'table.success.added': 'Đã thêm bàn thành công.',
    'table.success.deleted': 'Đã xóa bàn thành công.',
    'table.management.empty': 'Không có bàn nào được đăng ký',
    'table.management.edit_table': 'Sửa bàn',
    'table.management.add_new_table': 'Thêm bàn mới',
    'table.management.configure_desc': 'Cấu hình số bàn và sức chứa.',
    'table.management.table_number_label': 'Số bàn',
    'table.management.table_number_placeholder': 'vd: 1, 2, 3',
    'table.management.table_number_desc': 'Sẽ được hiển thị trên thẻ bàn.',
    'table.management.floor_label': 'Tầng',
    'table.management.floor_placeholder': 'vd: 1',
    'table.management.floor_desc': 'Bàn này nằm ở tầng nào?',
    'table.management.capacity_label': 'Sức chứa',
    'table.management.capacity_placeholder': 'vd: 4',
    'table.management.capacity_desc': 'Số khách tối đa cho bàn này.',
    'table.management.table_label': 'Bàn {number}',
    'table.management.edit_details': 'Sửa chi tiết',
    'table.management.delete_confirm': 'Bạn có chắc muốn xóa bàn {number}?',
    'table.management.saving': 'Đang lưu...',
    'table.management.save_changes': 'Lưu thay đổi',
    'table.management.add_table_button': 'Thêm bàn',
    'table.error.table_not_found': 'Không tìm thấy bàn',
    'table.error.cannot_delete_active': 'Không thể xóa bàn đang hoạt động. Vui lòng làm trống trước.',
    
    // OrderEntrySheet
    'order.entry.table_number': 'Bàn {number}',
    'order.entry.creating': 'Đang tạo đơn...',
    
    // WaitingListPanel Actions
    'wait.action.edit': 'Sửa',
    'wait.action.cancel': 'Hủy',
    'wait.action.delete': 'Xóa',
    'wait.saving': 'Đang lưu...',
    
    // LoginScreen
    'login.error.restaurant_load_failed': 'Không thể tải thông tin nhà hàng.',
    'login.error.restaurant_not_found': 'Không tìm thấy nhà hàng. Vui lòng kiểm tra ID nhà hàng.',
    'login.error.restaurant_id_required': 'Cần ID nhà hàng.',
    'login.mode.admin': 'Đăng nhập quản lý',
    'login.mode.pin': 'Đăng nhập POS (PIN)',
    'login.title.who_logging_in': 'Ai đang đăng nhập?',
    'login.pin.enter_pin': 'Nhập PIN',
    'login.success.welcome_back': 'Chào mừng trở lại, {name}!',
    
    // Notifications
    'notification.title': 'Thông báo',
    'notification.unread': 'Chưa đọc',
    'notification.mark_all_read': 'Đánh dấu tất cả đã đọc',
    'notification.new_order': 'Đơn hàng mới #{number}',
    'notification.table_placed_order': 'Bàn {number} đã đặt đơn hàng mới',
    'notification.water_request': 'Yêu cầu nước',
    'notification.table_needs_water': 'Bàn {number} cần nước',
    'notification.customer_request': 'Yêu cầu khách hàng',
    'notification.table_has_request': 'Bàn {number} có yêu cầu',
    'notification.payment_confirmed': 'Xác nhận thanh toán',
    'notification.table_paid': 'Bàn {number} đã thanh toán {amount}',
    'notification.shift_alert': 'Cảnh báo ca làm',
    'notification.break_time_starts': 'Giờ nghỉ bắt đầu sau {minutes} phút',
    'notification.just_now': 'Vừa xong',
    'notification.time_ago': '{minutes} phút trước',
    'notification.hour_ago': '{hours} giờ trước',
    'notification.no_more': 'Không còn thông báo nào',
    'notification.tab.all': 'Tất cả',
    'notification.tab.unread': 'Chưa đọc',
    'notification.tab.orders': 'Đơn hàng',
    'notification.tab.requests': 'Yêu cầu',
    'notification.tab.chat': 'Tin nhắn',
    'notification.tab.payment': 'Thanh toán',
    'notification.tab.other': 'Khác',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ko');

  const t = (key: string) => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
